"""empty message

Revision ID: cafb9fa61bc4
Revises: c05edeeb7683
Create Date: 2025-09-10 21:59:23.401270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cafb9fa61bc4'
down_revision: Union[str, Sequence[str], None] = 'c05edeeb7683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('settings', 'language',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('ru', 'en', name='language'),
               nullable=False,
               postgresql_using='language::language')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('settings', 'language',
               existing_type=sa.Enum('ru', 'en', name='language'),
               type_=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
