"""empty message

Revision ID: c05edeeb7683
Revises: 60f0ea11823e
Create Date: 2025-09-10 16:33:58.813355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c05edeeb7683'
down_revision: Union[str, Sequence[str], None] = '60f0ea11823e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_access_token_key'), 'users', type_='unique')
    op.drop_column('users', 'access_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('users_access_token_key'), 'users', ['access_token'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
