"""add Profits and Expenses tables

Revision ID: 60f0ea11823e
Revises: 2a0c2d28e562
Create Date: 2025-09-10 16:28:27.241353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60f0ea11823e'
down_revision: Union[str, Sequence[str], None] = '2a0c2d28e562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shop', sa.String(), nullable=True),
    sa.Column('sum', sa.Numeric(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_id'), 'expense', ['id'], unique=False)
    op.create_table('profit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('sum', sa.Numeric(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profit_id'), 'profit', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profit_id'), table_name='profit')
    op.drop_table('profit')
    op.drop_index(op.f('ix_expense_id'), table_name='expense')
    op.drop_table('expense')
    # ### end Alembic commands ###
